[media-configuration]
m5_authority = <<ADD_YOUR_IP_HERE>>:7778
format = FiveGMagJsonFormatter
cmmf = CmmfVodConfigFormatter
root_dir = /usr/share/nginx/html/m8
cmmf_root_dir = /etc/rt-5gms/cmmf-config
m8outputs = %(format)s(root_dir=%(root_dir)s);%(cmmf)s(root_dir=%(cmmf_root_dir)s)

