# Use Ubuntu 22.04 as a parent image
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    python3-pip \
    python3-venv \
    wget \
    default-jdk \
    && apt-get clean

# Clone the repository
RUN git clone --recurse-submodules https://github.com/5G-MAG/rt-5gms-application-provider

# Set working directory
WORKDIR /rt-5gms-application-provider

# Install Python dependencies
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install ./python

# Install Management UI
RUN python3 -m pip install -r management-ui/requirements.txt

# Copy the entrypoint script
COPY application-provider-entrypoint.sh /usr/local/bin/application-provider-entrypoint.sh

# Set execute permissions for the entrypoint script
RUN chmod +x /usr/local/bin/application-provider-entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/application-provider-entrypoint.sh"]
