# Use Ubuntu 22.04 as a parent image
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    python3-pip \
    python3-venv \
    wget \
    default-jdk \
    && apt-get clean

# Install Openresty
RUN apt-get -y install --no-install-recommends wget gnupg ca-certificates lsb-release && \
    wget -O - https://openresty.org/package/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/openresty.gpg && \
    ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then \
        echo "deb [arch=$ARCH signed-by=/usr/share/keyrings/openresty.gpg] http://openresty.org/package/arm64/ubuntu $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/openresty.list > /dev/null; \
    else \
        echo "deb [arch=$ARCH signed-by=/usr/share/keyrings/openresty.gpg] http://openresty.org/package/ubuntu $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/openresty.list > /dev/null; \
    fi && \
    apt-get update  && \
    apt-get -y install openresty

# Add Openresty version of nginx to the path
ENV PATH="/usr/local/openresty/nginx/sbin:$PATH"

# Disable and stop nginx and openresty services
RUN systemctl disable --now nginx.service openresty.service || true

# Clone the repository
RUN git clone --recurse-submodules https://github.com/5G-MAG/rt-5gms-application-server.git /5gms-application-server

# Set the working directory
WORKDIR /5gms-application-server

# Install Python dependencies
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install .

# Command to run the application
CMD ["5gms-application-server","-c","/etc/5gmag/as/conf/application-server.conf"]
