# Use an official Ubuntu as a parent image
FROM ubuntu:22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    python3-venv \
    python3-setuptools \
    python3-wheel \
    ninja-build \
    build-essential \
    flex \
    bison \
    libsctp-dev \
    libgnutls28-dev \
    libgcrypt-dev \
    libssl-dev \
    libidn11-dev \
    libmongoc-dev \
    libbson-dev \
    libyaml-dev \
    libnghttp2-dev \
    libmicrohttpd-dev \
    libcurl4-gnutls-dev \
    libtins-dev \
    libtalloc-dev \
    libpcre2-dev \
    curl \
    wget \
    default-jdk \
    cmake && \
    rm -rf /var/lib/apt/lists/*

# Install Meson
RUN python3 -m pip install meson

# Install additional Python packages
RUN python3 -m pip install build pyOpenSSL

# Clone the repository
RUN git clone --recurse-submodules https://github.com/5G-MAG/rt-5gms-application-function.git /opt/rt-5gms-application-function

# Set working directory
WORKDIR /opt/rt-5gms-application-function

# Update submodules
RUN git submodule update

# Build the application
RUN meson build && ninja -C build

# Install the application
RUN meson install --no-rebuild -C build

# Expose necessary ports (if any)
# EXPOSE <port_number>

# Command to run the application with the configuration file
CMD ["/usr/local/bin/open5gs-msafd", "-c", "/etc/open5gs/alternate-msaf.yaml"]
