# Use Ubuntu 22.04 as a parent image
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    python3-pip \
    python3-venv \
    wget \
    default-jdk \
    && apt-get clean

# Install Openresty
RUN wget -qO - https://openresty.org/package/pubkey.gpg | apt-key add - && \
    apt-get update && \
    apt-get install -y openresty && \
    apt-get clean

# Add Openresty version of nginx to the path
ENV PATH="/usr/local/openresty/nginx/sbin:$PATH"

# Disable and stop nginx and openresty services
RUN systemctl disable --now nginx.service openresty.service || true

# Clone the repository
RUN git clone --recurse-submodules https://github.com/5G-MAG/rt-5gms-application-server.git /5gms-application-server

# Set the working directory
WORKDIR /5gms-application-server

# Install Python dependencies
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install .

# Command to run the application
CMD ["5gms-application-server"]
