# Use an official Ubuntu as a parent image
FROM ubuntu:22.04

# Avoid any questions
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update && \
    apt install -y \
    git \
    python3-pip \
    python3-venv \
    python3-setuptools \
    python3-wheel \
    ninja-build \
    build-essential \
    flex \
    bison \
    libsctp-dev \
    libgnutls28-dev \
    libgcrypt-dev \
    libssl-dev  \
    libidn11-dev \
    libmongoc-dev \
    libbson-dev \
    libyaml-dev \
    libnghttp2-dev \
    libmicrohttpd-dev \
    libcurl4-gnutls-dev \
    libnghttp2-dev \
    libtins-dev \
    libtalloc-dev \
    libpcre2-dev \
    curl \
    wget \
    default-jdk \
    cmake

# Install Meson
RUN python3 -m pip install meson

# Install additional Python packages
RUN python3 -m pip install build pyOpenSSL

# Clone the repository
RUN git clone --recurse-submodules --branch test/docker https://github.com/5G-MAG/rt-5gms-application-function.git /rt-5gms-application-function

# Set working directory
WORKDIR /rt-5gms-application-function

# Update submodules
RUN git submodule update

# Build the application
RUN meson build -Dcpp_args=-Wno-error && ninja -C build

# Install the application
RUN meson install --no-rebuild -C build

# Command to run the application with the configuration file
CMD ["/usr/local/bin/open5gs-msafd", "-c", "/etc/open5gs/alternate-msaf.yaml"]
