services:

  db:
    container_name: db
    labels:
      monitor.group: "5GC NFs"
    image: "mongo:${MONGODB_VERSION}"
    command: "mongod --bind_ip 0.0.0.0 --port 27017"
    networks:
      5g-mag:
        aliases:
          - db.5g-mag.org
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  nrf:
    container_name: nrf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/nrf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/nrf.yaml"
    networks:
      5g-mag:
        aliases:
          - nrf.5g-mag.org
    configs:
      - source: nrf_config
        target: /etc/open5gs/custom/nrf.yaml

  ausf:
    container_name: ausf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/ausf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/ausf.yaml"
    networks:
      5g-mag:
        aliases:
          - ausf.5g-mag.org
    configs:
      - source: ausf_config
        target: /etc/open5gs/custom/ausf.yaml
    depends_on:
      - nrf

  udm:
    container_name: udm
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/udm:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/udm.yaml"
    networks:
      5g-mag:
        aliases:
          - udm.5g-mag.org
    configs:
      - source: udm_config
        target: /etc/open5gs/custom/udm.yaml
    depends_on:
      - nrf

  udr:
    container_name: udr
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/udr:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/udr.yaml"
    restart: unless-stopped
    networks:
      5g-mag:
        aliases:
          - udr.5g-mag.org
    configs:
      - source: udr_config
        target: /etc/open5gs/custom/udr.yaml
    depends_on:
      - db
      - nrf

  nssf:
    container_name: nssf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/nssf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/nssf.yaml"
    networks:
      5g-mag:
        aliases:
          - nssf.5g-mag.org
    configs:
      - source: nssf_config
        target: /etc/open5gs/custom/nssf.yaml
    depends_on:
      - nrf

  bsf:
    container_name: bsf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/bsf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/bsf.yaml"
    networks:
      5g-mag:
        aliases:
          - bsf.5g-mag.org
    configs:
      - source: bsf_config
        target: /etc/open5gs/custom/bsf.yaml
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/pcf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/pcf.yaml"
    restart: unless-stopped
    networks:
      5g-mag:
        aliases:
          - pcf.5g-mag.org
    configs:
      - source: pcf_config
        target: /etc/open5gs/custom/pcf.yaml
    depends_on:
      - db
      - nrf

  amf:
    container_name: amf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/amf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/amf.yaml"
    networks:
      5g-mag:
        aliases:
          - amf.5g-mag.org
    configs:
      - source: amf_config
        target: /etc/open5gs/custom/amf.yaml
    depends_on:
      - nrf

  smf:
    container_name: smf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/smf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/smf.yaml"
    networks:
      5g-mag:
        aliases:
          - smf.5g-mag.org
    configs:
      - source: smf_config
        target: /etc/open5gs/custom/smf.yaml
    depends_on:
      - nrf

  upf:
    container_name: upf
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/upf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/upf.yaml"
    networks:
      5g-mag:
        aliases:
          - upf.5g-mag.org
    configs:
      - source: upf_config
        target: /etc/open5gs/custom/upf.yaml
    privileged: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - nrf

  webui:
    container_name: webui
    labels:
      monitor.group: "5GC NFs"
    image: "ghcr.io/5g-mag/webui:${OPEN5GS_VERSION}"
    environment:
      - DB_URI=mongodb://db.5g-mag.org/open5gs
      - PORT=9999
      - HOSTNAME=0.0.0.0
      - NODE_ENV=dev
    command: "run dev"
    networks:
      5g-mag:
        aliases:
          - webui.5g-mag.org
    depends_on:
      - db
    ports:
      - "0.0.0.0:9999:9999/tcp"


networks:
  5g-mag:
    external: true

volumes:
  db_data:
    name: open5gs_db_data
    external: true
  db_config:
    name: open5gs_db_config
    external: true

configs:
  nrf_config:
    file: ./configs/nrf.yaml
  ausf_config:
    file: ./configs/ausf.yaml
  udm_config:
    file: ./configs/udm.yaml
  udr_config:
    file: ./configs/udr.yaml
  nssf_config:
    file: ./configs/nssf.yaml
  bsf_config:
    file: ./configs/bsf.yaml
  pcf_config:
    file: ./configs/pcf.yaml
  amf_config:
    file: ./configs/amf.yaml
  smf_config:
    file: ./configs/smf.yaml
  upf_config:
    file: ./configs/upf.yaml
