services:
    application-server:
        build:
            context: ./
            dockerfile: Dockerfile-Application-Server
        container_name: 5gms-application-server
        ports:
            - "8080:80" # Maps port 80 on the container to port 8080 on the host
        networks:
            - 5gms-network

    application-function:
        build:
            context: ./
            dockerfile: Dockerfile-Application-Function
        container_name: 5gms-application-function
        ports:
            - "5555:5555"
            - "7778:7778"
        volumes:
            - ./msaf.yaml:/etc/open5gs/alternate-msaf.yaml
        networks:
            - 5gms-network

networks:
    5gms-network:
        driver: bridge
